### ISSUE TITLE
Error "Invalid RedGifs URL"

### ISSUE THREAD

**Issue by qmka** [scrazzz/redgifs#12]
### Summary

The program gives an error when loading a file

### Reproduction Steps

Trying to download a file using ID according to instruction. Instead of loading the file, the program gives aTypeerror. It appeared recently, a week ago everything was downloaded correctly. 
Does not work even with the example from the repository /examples/download.py. Probably some changes on RedGifs site.

### Expected Result

Downloading a file

### Actual Result

![issue1](https://user-images.githubusercontent.com/43089677/219947136-efff46f3-af42-4d54-986f-fbe9e66c7c3c.png)

### System Information

- Python v3.10.7-final
- redgifs v1.5.0-alpha
    - redgifs metadata: v1.5.1
- aiohttp v3.7.4.post0
- system info: Linux 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023

### Checklist

- [X] I have searched all open and closed issues for any duplicates.

**Comment by scrazzz** [comment]
Hello, thanks for reporting this issue. I have recently fixed the regex for the thumbnail (4c3606b). So this issue should not exist on the next versions.

Can you use the latest version which is on GitHub? You can do that by updating `redgifs` using the command below:
```console
pip install -U git+https://github.com/scrazzz/redgifs
```

**Comment by qmka** [comment]
Updated, now it works. Thanks so much!

**Comment by scrazzz** [comment]
Alright.
