### ISSUE TITLE
Mass Downloader

### ISSUE THREAD

**Issue by maxmartin10** [scrazzz/redgifs#17]
### Summary

if i want to download all video from one user i cant,

### The Problem

if i want to do mass download then i have give all videos links.

### The Ideal Solution

IF you upload mass downloaded 

For Ex: This https://www.redgifs.com/users/XXXX if this user have 400 GIFS

then i want to download all in once. this can make easy.

**Comment by scrazzz** [comment]
Thanks for the suggestion. I'll see what I can do. 👍

**Comment by maxmartin10** [comment]
> Thanks for the suggestion. I'll see what I can do. 👍

when you update please let me know 

thanks

**Comment by scrazzz** [comment]
Hello, I have updated `CreatorResult`  to now include the user's GIFs.

----

Here's what you have to do:

1. Install `redgifs` from GitHub.
```
python -m pip install -U git+https://github.com/scrazzz/redgifs
```
2. Check the new `download_user.py` example: https://github.com/scrazzz/redgifs/blob/main/examples
3. Profit

If you encounter any error please let me know. If you need help join the Discord server on the README.

**Comment by maxmartin10** [comment]
so i have run this CMD on kali:

redgifs https://www.redgifs.com/users/slootsgonnasloot1

**Comment by scrazzz** [comment]
No, check step 2. You have to use the code there. Now that you mentioned it, I may support this for CLI usage later.

**Comment by maxmartin10** [comment]
so i run this cmd:

python3 download_user.py https://www.redgifs.com/users/slootsgonnasloot1
<-- getting error.

and your discord link is expired please send me a new link.

**Comment by scrazzz** [comment]
Looks like you don't know basic python.
https://discord.gg/yNsUTuXvzn

**Comment by maxmartin10** [comment]
Yeah. `you are right.
