### ISSUE TITLE
Search using tags example

### ISSUE THREAD

**Issue by acctfpn** [scrazzz/redgifs#21]
### Summary

Create an example of how to search using one or more tags

### The Problem

The [docs](https://redgifs.readthedocs.io/en/latest/api.html?highlight=tag#redgifs.API.search) tell me that an instance of Tags can be used for searching.
`search_text (str) – The GIFs to search for. Can be a string or an instance of [Tags]`

I tried a few things but I'm unable to create an instance of Tags.

### The Ideal Solution

Create an example of how to do this.

**Comment by scrazzz** [comment]
Using tags to search is a bit finicky. I personally don't advice you to use it unless you really need to. Nonetheless, I have added an example for it: cf3d4b0f202a9057a3fd3e1def664a8923a12159.

**Comment by acctfpn** [comment]
Thanks, my reasoning for using tags is that searching normally can often give results that do not match.
TBH this happens using the webpage too, even tags are not always accurate, but worth a try.
