### ISSUE TITLE
No sound on downloaded media

### ISSUE THREAD

**Issue by kumpelblase97** [scrazzz/redgifs#24]
### Summary

When using the cli-tool the downloaded media has no sound

### Reproduction Steps

In terminal: redgifs <media_url> 

### Expected Result

Download the Media as a mp4 with sound

### Actual Result

Download the Media as a mp4 without sound

### System Information

 redgifs --version
- Python v3.10.9-final
- redgifs v1.7.2-final
- aiohttp v3.8.6
- system info: Darwin 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched all open and closed issues for any duplicates.

**Comment by scrazzz** [comment]
You probably opened the download video in Visual Studio Code. It's an issue with VS Code not playing the sound.

**Comment by scrazzz** [comment]
@jehannes Some videos don't have sound and that's intentional. Check the [`has_audio`](https://redgifs.readthedocs.io/en/stable/api.html#redgifs.models.GIF.has_audio) attribute to know if the GIF has sound or not.
