### ISSUE TITLE
`search_creators` with tag result incomplete and missing entries

### ISSUE THREAD

**Issue by JThreepw** [scrazzz/redgifs#27]
### Summary

The `search_creators` with a tag result does not contain all creators that have content with that tag and the creators that are returned are missing entries

### The Problem

When using `search_creators`with a tag, the result
a) does not contain all creators that have content with that tag. Like if I search on the website for a tag, the creator of almost every result on the website is not in the API result with the same tag.
b) is missing entries, at least for `description` and `links`, those are not filled like they would be if I query a single creator.

### The Ideal Solution

`search_creators`, when called with a tag, should return all creators that have content with that tag. Ideally the result contains a count of content of each creator that matches that tag.
Also the fields `links` and `description` should be filled correctly.

**Comment by scrazzz** [comment]
Please open a **bug report** with a suitable explanation and code. You just opened a feature request issue.
