### ISSUE TITLE
Difficulty in using link generated by get_gif(id) function with download(url,file_name) function

### ISSUE THREAD

**Issue by CelebStalker** [scrazzz/redgifs#8]
URL given by get_gif(id) function unable to be used with download function.
![Screenshot 2022-09-10 192914](https://user-images.githubusercontent.com/113247477/189486815-4485e5da-9fae-4feb-8f36-5a71e2e8ca4d.png)

**Comment by scrazzz** [comment]
Hello, thanks for opening an issue to report this bug.

This seems like an API error with RedGifs. They stated in their documentation that you would receive a proper URL of their new change (See issue #7 and [the official docs](https://github.com/Redgifs/api/wiki/Requesting-media-links#how-it-works)).

I'll let RedGifs know about this issue and will get back to you later.

**Comment by scrazzz** [comment]
A workaround for this right now is by replacing `thumbs2` with `thumbs3` in the URL.

```py
from redgifs import API

api = API()
url = api.get_gif('simplefunctionalamericanwirehair').urls.hd

new_url = url.replace('thumbs2', 'thumbs3')
print(new_url)
````

Keep in mind that this may stop working at anytime.

**Comment by sergeinaumoff** [comment]
> A workaround for this right now is by replacing `thumbs2` with `thumbs3` in the URL.
> 
> ```python
> from redgifs import API
> 
> api = API()
> url = api.get_gif('simplefunctionalamericanwirehair').urls.hd
> 
> new_url = url.replace('thumbs2', 'thumbs3')
> print(new_url)
> 
> api.download(new_url, 'vid.mp4')
> ```
> 
> Keep in mind that this may stop working at anytime.

Thank you!
I noticed that it possible to download video if use 'search' method and take 'thumbs4' URL with signature, for example from first element of Gifs. Unfortunately, it doesn't work if I get 'thumbs4' URL from page directly (using BeautifulSoup) and try to use 'download' method.

**Comment by CelebStalker** [comment]
It probably has to do with issue #7 
Some kind of validation the website has introduced.

**Comment by scrazzz** [comment]
Looks like this issue has been fixed
![IMG](https://user-images.githubusercontent.com/70033559/189797079-e992b577-fb72-42c1-abc7-99281b7730e7.jpg)
